### PR TITLE
Fest Template

### LINKED ISSUE #48: Main Website - Create Template common landing page for Student Fests with no website
* Create a general template for a landing page for events like Crrescendo, Bharat Darshan, etc which display information(text, images and videos) of the fest and allow the users to obtain information at the same time! This is to be done something along the lines of how Google Websites work! 
* Please make sure you use all your creativity in this! In case you feel it is too much work for one week, please do let me know! 
* Prepare a mock-up before coding. 
* Also discuss and finalize amongst yourselves about this!

### PR DESCRIPTION
**Pull request by MJ10**
Resolves #48 
Template for fests with no website. 

**Screenshots**
fest xyz
fest xyz 1

### CODE REVIEW

**Review by Hrily — CHANGES_REQUESTED** [review]
Please change colors of title and subtitle.
Subtitle not visible in small screens.
You can add shadow to the text to make it visible.

**Review by sbshah97 — CHANGES_REQUESTED** [review]
KIndly use different fonts rather than the Default font that you've used!

**Comment by MJ10** [comment]
Changed the font and added Shadows to Title and Subtitle.
Updated the screenshots in the description

**Review by sbshah97 — APPROVED** [review]

**Comment by sbshah97** [comment]
@hrily kindly review

**Review by Hrily — APPROVED** [review]

**Pull request merged**
