### PR TITLE
Department events #28

### PR DESCRIPTION
**Pull request by anumehaagrawal**
mob1
mob3
desk

Events page #28 
img one
img two

### CODE REVIEW

**Comment by sbshah97** [comment]
@anumehaagrawal work on indentation on the second screenshot
Near all those NITK Logos. 
Apart from that good work!

**Review by sbshah97 — CHANGES_REQUESTED** [review]
Add indentation to images evenly. Also add screen-shots for mobile version.

**Review by sbshah97 — DISMISSED** [review]

**Review by Hrily — CHANGES_REQUESTED** [review]
Please remove the title with brown background, It's redundant as the tab shows the title.
Also please fix the tabs in small screen, it's not responsive.

**Comment by sbshah97** [comment]
Kindly finish off what @Hrily requested. I'll merge your request after that!

**Comment by anumehaagrawal** [comment]
Corrections made :
ne2
ne3
ne4

**Review by sbshah97 — APPROVED** [review]
Work done looks good to me!

**Review by Hrily — APPROVED** [review]

**Pull request merged**
