### PR TITLE
Department Contact Us Updated

### PR DESCRIPTION
**Pull request by rashika97**
#29 the department details weren't there in the previous pr and the code is optimized for mobile as well.
desktop shots:-
screenshot from 2017-05-05 18-53-01
screenshot from 2017-05-05 18-53-06
screenshot from 2017-05-05 18-53-11
mobile shots:-
screen shot 2017-05-05 at 18 51 14
screen shot 2017-05-05 at 18 51 22
screen shot 2017-05-05 at 18 51 28
screen shot 2017-05-05 at 18 51 40
screen shot 2017-05-05 at 18 51 44

### CODE REVIEW

**Review by sbshah97 — COMMENTED** [review]
Good work! But please try to maintain an indentation of two spaces for all the code from next time!

**Review by sbshah97 — APPROVED** [review]

**Comment by rashika97** [comment]
okay! thanks! will keep that in mind.

**Comment by sbshah97** [comment]
Oye header ka colour kya daal diya!

**Review by sbshah97 — CHANGES_REQUESTED** [review]
Please change Header colour in Desktop version of the website!

**Comment by rashika97** [comment]
okay!

**Review by sbshah97 — APPROVED** [review]

**Pull request merged**
