### PR TITLE
Admission page added

### PR DESCRIPTION
**Pull request by sbshah97**
* Page for various programmes in NITK added!
#57 resolved
* Screenshots
nitk surathkal
screenshot from 2017-05-12 14-02-07
screenshot from 2017-05-12 14-02-22
screenshot from 2017-05-12 14-02-29
screenshot from 2017-05-12 14-02-34
screenshot from 2017-05-12 14-02-38

### CODE REVIEW

**Comment by MJ10** [comment]
Separated JS and CSS.
Properly indented code.
Optimized images

**Comment by sbshah97** [comment]
Mobile version screenshots?

**Comment by MJ10** [comment]
The first one is a mobile screenshot @salman-bhai

**Review by sbshah97 — COMMENTED** [review]
Good work @MJ10

**Pull request merged**
