### PR TITLE
Projects(Sponsored+Ongoing)

### PR DESCRIPTION
**Pull request by mishal23**
Desktop View:-
screenshot 4

screenshot 5

screenshot 6

Mobile View:-

screenshot 2
screenshot 3

### CODE REVIEW

**Comment by mohittahiliani** [comment]
@mishal23 - Good job!

Some comments:
+ Do we need a Department column? The data listed there would be related to one department only.
+ It would be better to show the number of Completed and Ongoing project inside brackets, in the tabs itself. For example, one tab name can be Completed (9), and the other one Ongoing (12). These numbers would be for the selected department.
+ Mobile view should be improved. Part of the table data is not visible.

Hope it helps.

**Comment by mishal23** [comment]
@mohittahiliani Sir - The purpose of including the department column was that initially all the department projects be displayed and on filtering from the select option the projects of the department be displayed , as I thought it might not look good that no projects be seen on page been loaded.

I'll try to improve on the rest of the points.

**Comment by mohittahiliani** [comment]
@mishal23 - thanks for letting me know. In that case, let the Department column appear in the table only until one department is selected from the drop down.

**Comment by akshayrvnkr** [comment]
@mishal23 @salman-bhai I guess you could try having an option to display the important details like project title compulsorily and then give an option to expand the details as shown below:

Collapsed
Expanded

(Hope @salman-bhai doesn't mind :P )

**Comment by sbshah97** [comment]
@akshayrvnkr even if I would mind wouldn't make a difference. Not as much swag as you. 😛

**Review by sbshah97 — CHANGES_REQUESTED** [review]
Make changes as suggested by @akshayrvnkr

**Comment by mishal23** [comment]
Changes made:-

- As suggested by @mohittahiliani Sir , Number of projects have been added in the completed/ongoing tab
- As suggested by @akshayrvnkr , Project titles be displayed and for more details expand.
Changed Desktop View:-
screenshot 12

screenshot 13

Changed Mobile View:-

screenshot 10

screenshot 11

**Review by sbshah97 — APPROVED** [review]

**Pull request merged**
