### PR TITLE
Department courses

### PR DESCRIPTION
**Pull request by MJ10**
Department Courses page. #11 
**Screenshots**:
nitkwss8
nitkwss1
127 0 0 1-4040-department_courses html nexus 6p
127 0 0 1-4040-department_courses html ipad
127 0 0 1-4040-course_details html nexus 6p
127 0 0 1-4040-course_details html ipad

### CODE REVIEW

**Comment by sbshah97** [comment]
@MJ10 Where will Course Details be displayed! Have you done a template for that as well?

**Review by sbshah97 — CHANGES_REQUESTED** [review]
Add course details HTML page in the same PR and send it back!

**Comment by MJ10** [comment]
@salman-bhai I did not know I had to make the course details page too. I'll make it and add it to the PR

**Comment by MJ10** [comment]
@salman-bhai made the changes :+1:

**Pull request merged**
